### ISSUE TITLE
Selection position issue with bootstrap 4

### ISSUE THREAD

**Issue by nunesvictor** [yourlabs/django-autocomplete-light#1055]
Hi,

I'm heaving some trouble with the position of the selected element with dal.

Look at my example: 
![select2](https://user-images.githubusercontent.com/5093514/46167757-0a031c80-c26d-11e8-9728-c1ff056141f0.png)
The upper one is a autocomplete.ModelSelect2 widget, the bottom one is a ordinary select2.

Looking the HTML of them both they look close to each other.

I don't have any templateResult or templateFormat modifications on any of them.

Tried with both django-bootstrap4 and django-crispy-forms and the result is about the same.

----

My setup:

- Django==2.1.1
- django-autocomplete-light==3.3.2
- django-bootstrap4==0.0.7
- django-crispy-forms==1.7.2

**Comment by partofthething** [comment]
I find that if I change the line-height to 16px in `select2.css` it is much better. 

```css
  .select2-container--default .select2-selection--single .select2-selection__rendered {
    color: #444;
    line-height: 28px; }
```
I don't know, however, where the appropriate place to override this would be in this scenario.
