### ISSUE TITLE
bug on commit 517999

### ISSUE THREAD

**Issue by agliottone** [yourlabs/django-autocomplete-light#265]
hi,
this code:
```javascript
    this.input.parents().filter(function() {
        return $(this).css('overflow') === 'hidden';
   }).first().css('overflow', 'visible');
```
 of this changeset:
https://github.com/yourlabs/django-autocomplete-light/commit/517999a2e9ad880032679d808d72d2ece0b1f347#diff-02e96c218abe02988d4453de4dd92199

broke my form
![screenshot from 2014-03-26 11 23 22](https://f.cloud.github.com/assets/1611152/2523446/5437b968-b4d1-11e3-8d3e-c4065c5d6eb9.png)

hi have resolved with:
```css
fieldset .form-row {
    overflow: visible !important;
    min-height: 26px;
}
```
do you know if this can impact badly in other parts? in case it's acceptable could this be integrated autocomplete_light?
